common: android: fix compile error if only enable ab system
error: ‘reset_cpu_if_android_ab’ defined but not used
[-Werror=unused-function]

Signed-off-by: Jason Zhu <jason.zhu@rock-chips.com>
Change-Id: I724ea99df27f9f572aa0913491eddb2b5e248e38