[MIPS] Remove inline asm string functions
Stop using inline string functions on MIPS as other ARCHs do so,
since the optimized inline asm versions are not small.

This change is triggered by a following MIPS build error:
common/libcommon.a(exports.o)(.text+0xdc): In function `jumptable_init':
common/exports.c:32: undefined reference to `strcmp'
make: *** [u-boot] Error 1

Signed-off-by: Shinya Kuribayashi <shinya.kuribayashi@necel.com>