usb: dwc3: get rid of debug compile error
When enable debug option to compile, it will give the
following error, this patch is used to get rid of it.

error: ‘flags’ is used uninitialized in this function [-Werror=uninitialized]

Change-Id: Iba4cd59ab28eb7a48490e45842541f0418239e17
Signed-off-by: William Wu <william.wu@rock-chips.com>