UPSTREAM: atomic-long: Fix warnings on arm64
Several inline functions in this file reference undefined functions in
U-Boot.  For example:

atomic-long.h:73:9: warning: implicit declaration of function
'atomic64_sub_and_test'
atomic-long.h:80:9: warning: implicit declaration of function
'atomic64_dec_and_test'
atomic-long.h:87:9: warning: implicit declaration of function
'atomic64_inc_and_test'

Handle this the same as the 32 bit build by wrapping these functions in
a __UBOOT__ check.

Signed-off-by: Bradley Bolen <bradleybolen@gmail.com>
(cherry picked from commit 9c3264ce40130966897fb9c1b91c120f588531d0)
Signed-off-by: Joseph Chen <chenjh@rock-chips.com>
Change-Id: Ie1c319851ab53cd23473dfae74d29528b34c318f