usb/gadget: Fix compile error due to invalid cast from pointer
../drivers/usb/gadget/s3c_udc_otg.c: In function ‘s3c_udc_probe’:
../drivers/usb/gadget/s3c_udc_otg.c:808:8: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
    reg = (struct s3c_usbotg_reg *)pdata->regs_otg;
          ^
../drivers/usb/gadget/s3c_udc_otg.c:824:22: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
    dev->dma_addr[i] = (dma_addr_t) dev->dma_buf[i];
cc1: all warnings being treated as errors                    ^

Change-Id: Ic65cacbd5879f215725f2d999c2bed53c73fccf7
Signed-off-by: Dongjin Kim <tobetter@gmail.com>