usb: phy: rockchip: fix implicit definition warning
When make with rock_defconfig, compile warning for the
following implicitly defined function are raised due to
a missing include directive:

  drivers/usb/phy/rockchip_usb2_phy.c: In function ‘otg_phy_parse’:
  drivers/usb/phy/rockchip_usb2_phy.c: 102:10: error:
  implicit declaration of function ‘fdt_translate_address’ [-Werror=implicit-function-declaration]
  addr = fdt_translate_address(blob, node, reg);
          ^~~~~~~~~~~~~~~~~~~~~
This change fixes this by including <fdt_support.h>.

And this patch also fixes the following compile error:

  drivers/usb/phy/rockchip_usb2_phy.c:96:1: error:
  label ‘retry’ defined but not used [-Werror=unused-label]

Change-Id: Ia82d0ff02b0f528ddde8a553d457c6c0cb763680
Signed-off-by: William Wu <william.wu@rock-chips.com>