lib: avb: avb_atx_validate: fix crypto sha512 fail
The new crypto-v2 drivers requires total data length before sha init,
let's add it to avoid issue:

  ...
  Vboot=0, AVB images, AVB verify
  read_is_device_unlocked() ops returned that device is LOCKED
  total length(0x00000000) != init length(0xeb9f6290)!
  avb_rsa.c:285: ERROR: Hash check failed.
  avb_atx_validate.c:173: ERROR: Invalid certificate signature.
  avb_atx_validate.c:199: ERROR: Invalid PIK certificate.
  avb_slot_verify.c:865: ERROR: vbmeta: Public key used to sign data rejected.
  AVB verify failed
  ...

Fixes: (5b0bc49177 lib: avb: support crypto sha256/512)

Signed-off-by: Joseph Chen <chenjh@rock-chips.com>
Change-Id: I276041a8b5faadac8c95622f77888a5447ed3a71