usb/gadget: Fix compile error due to invalid format symbol
../drivers/usb/gadget/f_mass_storage.c: In function ‘do_write’:
../drivers/usb/gadget/f_mass_storage.c:977:12: error: format ‘%d’ expects
argument of type ‘int’, but argument 2 has type ‘ssize_t’ [-Werror=format=]
            amount);

Change-Id: I5549503734d3490e774b783114c5c0b6712a6615
Signed-off-by: Dongjin Kim <tobetter@gmail.com>